name: build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-22.04
        name: ${{ matrix.image }}

        strategy:
            matrix:
                image:
                -   tayloraswift/5.10.0-amazonlinux2023:latest
        steps:
            -   name: checkout repository
                uses: actions/checkout@v3

            -   name: set up mock deployments
                run: |
                    docker compose -f Guides/docs.docc/local/docker-compose.yml up -d

            -   name: initialize replica set
                run: |
                    timeout 60s bash -c \
                    'until docker exec -t unidoc-mongod-container \
                    /bin/mongosh --file /unidoc-rs-init.js; do sleep 1; done'

            -   name: build and test
                run: |
                    docker run -t --rm \
                        --network=unidoc-test \
                        --name swift-environment \
                        --user root \
                        -v $PWD:/swift/swift-unidoc \
                        -w /swift/swift-unidoc \
                        ${{ matrix.image }} \
                        /bin/bash .github/pipeline
