name: build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    linux:
        runs-on: ubuntu-22.04
        name: ${{ matrix.image }}

        strategy:
            matrix:
                image:
                -   swiftlang/swift:nightly-5.8-amazonlinux2
                -   swiftlang/swift:nightly-5.8-jammy
        steps:
            -   name: checkout repository
                uses: actions/checkout@v3
            
            -   name: build and test
                run: |
                    docker run -t --rm \
                        --name swift-environment \
                        -v $PWD:/swift-unidoc \
                        -w /swift/swift-unidoc \
                        ${{ matrix.image }} \
                        /bin/bash $(echo .github/pipeline)
